DROP TABLE parking IF EXISTS;

CREATE TABLE parking(
id INTEGER IDENTITY PRIMARY KEY,
name VARCHAR(30) NOT NULL,
nbPlaceTotal INTEGER NOT NULL,
longitude DOUBLE NOT NULL,
latitude DOUBLE NOT NULL,
cityname VARCHAR(30)NOT NULL
)