spring:
  sql:
   init:
    mode: always
  mvc: 
   pathmatch:
    matching-strategy: ant_path_matcher
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  cloud:
    config:
      uri: http://localhost:8888
  application:
    name: parkings-service
---
spring:
  profiles: docker
  cloud:
    config:
      uri: http://config-server:8888   
      
